import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adesh Rai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="m-4 my-8 grid  gap-4 xl:grid-cols-12 lg:grid-cols-12" >
       <div className=" xl:col-span-2 lg:col-span-1 lg:block hidden " ></div>
       <div className="h-screen  lg:col-span-10 xl:col-span-8" >
          <Navbar/>
       {children}
      </div>
       <div className="xl:col-span-2 lg:col-span-1 lg:block hidden " ></div>
      </div>
      </body>
    </html>
  );
}
